[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-T", 
    "-C", "link-arg=simple.ld",
    "-C", "link-arg=--nmagic",
    "-C", "relocation-model=static",
    "-C", "link-arg=-no-pie"
]
